/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"
#include "GPIO_interface.h"
#include"RCC_interface.h"
#include"GPIO_config.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void SmallDelay (void)
{
    for(u32 s = 0 ; s<200 ; s++ )
    {
        asm("NOP");
    }
}
int main(void)
{
	RCC_voidSysClockInit();
	RCC_voidEnablePerClk(RCC_AHB1,AHB1_GPIOA );
	GPIO_u8SetPinDirection(GPIO_u8_PORTA, GPIO_u8_PIN0, GPIO_u8_PIN_INPUT);
	GPIO_u8SetPinDirection(GPIO_u8_PORTA, GPIO_u8_PIN1, GPIO_u8_PIN_INPUT);
	GPIO_u8SetPinDirection(GPIO_u8_PORTA, GPIO_u8_PIN2, GPIO_u8_PIN_INPUT);
	GPIO_u8SetPinDirection(GPIO_u8_PORTA, GPIO_u8_PIN3, GPIO_u8_PIN_OUTPUT);
	GPIO_u8SetPinDirection(GPIO_u8_PORTA, GPIO_u8_PIN4, GPIO_u8_PIN_OUTPUT);
	GPIO_u8SetPinDirection(GPIO_u8_PORTA, GPIO_u8_PIN5, GPIO_u8_PIN_OUTPUT);

	u8 Local_u8Pin0Value ;
	u8 Local_u8Pin1Value ;
	u8 Local_u8Pin2Value ;

	for(;;)
	{
		GPIO_u8SetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN3 , GPIO_u8_PIN_LOW);
		GPIO_u8SetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN4 , GPIO_u8_PIN_LOW);
		GPIO_u8SetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN5 , GPIO_u8_PIN_LOW);
		GPIO_u8GetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN0 , &Local_u8Pin0Value);
		GPIO_u8GetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN1 , &Local_u8Pin1Value);
		GPIO_u8GetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN2 , &Local_u8Pin2Value);
		if(Local_u8Pin0Value==0)
			GPIO_u8SetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN3 , GPIO_u8_PIN_HIGH);
		if(Local_u8Pin1Value==0)
					GPIO_u8SetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN4 , GPIO_u8_PIN_HIGH);
		if(Local_u8Pin2Value==0)
					GPIO_u8SetPinValue (GPIO_u8_PORTA , GPIO_u8_PIN5 , GPIO_u8_PIN_HIGH);
		SmallDelay();

	}
}
